spring:
  application:
    name: onoff-test
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:memdb;DB_CLOSE_DELAY=0
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  liquibase:
    change-log: classpath:db/master.xml
  security:
    user:
      name: user
      password: Password_123!
